package ua.kpi.mobiledev.exception;

public enum ErrorCode {
    USER_NOT_FOUND_WITH_ID,
    USER_ALREADY_EXISTS,
    REGISTRATION_GENERAL_SYSTEM_EXCEPTION,

    ORDER_NOT_FOUND_WITH_ID,
    INVALID_ORDER_STATUS,
    ILLEGAL_ORDER_STATUS_TRANSITION,
    USER_CANNOT_CHANGE_ORDER_STATUS,
    TAXI_DRIVER_CANT_ADD_ORDER,
    USER_SHOULD_BE_ORDER_OWNER_WHEN_ADD,
    USER_IS_NOT_ORDER_OWNER,
    DRIVER_CANNOT_PERFORM_OPERATION,
    LICENSE_SCAN_PROCESSING_FAILED,

    INVALID_REQUIREMENT_ID,
    REQUIREMENT_VALUE_IS_NULL,

    CANNOT_UPDATE_EMAIL,
    CANNOT_UPDATE_USER_TYPE,
    INVALID_MOBILE_NUMBER_ID,

    DEFAULT_EXCEPTION_MESSAGE,

    TEST_CODE
}
